// <auto-generated />
using System;
using ECommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722102959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.Catalog.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IconPhotoId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("icon_photo_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCategoryId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("slug")
                        .UseCollation("ascii_bin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("IconPhotoId")
                        .HasDatabaseName("ix_categories_icon_photo_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.HasIndex("ParentCategoryId", "IsActive", "SortOrder")
                        .HasDatabaseName("ix_categories_parent_category_id_is_active_sort_order");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("features_json");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<decimal>("RatingAverage")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("rating_average");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int")
                        .HasColumnName("review_count");

                    b.Property<string>("SellerProfileId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("seller_profile_id");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("IsActive", "Price")
                        .HasDatabaseName("ix_products_is_active_price");

                    b.HasIndex("IsActive", "CategoryId", "CreatedAtUtc")
                        .HasDatabaseName("ix_products_is_active_category_id_created_at_utc");

                    b.HasIndex("SellerProfileId", "IsActive", "CreatedAtUtc")
                        .HasDatabaseName("ix_products_seller_profile_id_is_active_created_at_utc");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_price", "price > 0");

                            t.HasCheckConstraint("ck_products_rating", "rating_average >= 0 AND rating_average <= 5");

                            t.HasCheckConstraint("ck_products_stock", "stock >= 0");
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.ProductPhoto", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("product_id");

                    b.Property<string>("PhotoId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("photo_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.HasKey("ProductId", "PhotoId")
                        .HasName("pk_product_photos");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_product_photos_photo_id");

                    b.HasIndex("ProductId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_product_photos_product_id_display_order");

                    b.ToTable("product_photos", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("customer_account_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("product_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("CustomerAccountId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_customer_account_id_product_id");

                    b.HasIndex("ProductId", "IsActive", "CreatedAtUtc")
                        .HasDatabaseName("ix_reviews_product_id_is_active_created_at_utc");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_rating", "rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.ReviewPhoto", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("review_id");

                    b.Property<string>("PhotoId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("photo_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.HasKey("ReviewId", "PhotoId")
                        .HasName("pk_review_photos");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_review_photos_photo_id");

                    b.HasIndex("ReviewId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_review_photos_review_id_display_order");

                    b.ToTable("review_photos", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Fulfillment.Shipment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered_at_utc");

                    b.Property<string>("OrderPackageId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("order_package_id");

                    b.Property<DateTime?>("ShippedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("shipped_at_utc");

                    b.Property<string>("ShippingCarrierId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("shipping_carrier_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("tracking_number");

                    b.Property<string>("TrackingUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("tracking_url");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.HasIndex("OrderPackageId")
                        .IsUnique()
                        .HasDatabaseName("ix_shipments_order_package_id");

                    b.HasIndex("ShippingCarrierId", "TrackingNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_shipments_shipping_carrier_id_tracking_number");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Fulfillment.ShippingCarrier", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("code")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<int>("EstimatedDeliveryDays")
                        .HasColumnType("int")
                        .HasColumnName("estimated_delivery_days");

                    b.Property<decimal>("FlatFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("flat_fee");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoPhotoId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("logo_photo_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("name");

                    b.Property<string>("TrackingUrlTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("tracking_url_template");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_shipping_carriers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_shipping_carriers_code");

                    b.HasIndex("LogoPhotoId")
                        .HasDatabaseName("ix_shipping_carriers_logo_photo_id");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_shipping_carriers_is_active_name");

                    b.ToTable("shipping_carriers", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.AccessTokenRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("account_id");

                    b.Property<int>("AccountSecurityVersion")
                        .HasColumnType("int")
                        .HasColumnName("account_security_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("IssuedByIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("issued_by_ip");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("jti")
                        .UseCollation("ascii_bin");

                    b.Property<string>("RefreshSessionId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("refresh_session_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserAgentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("user_agent_hash");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_access_token_records");

                    b.HasIndex("Jti")
                        .IsUnique()
                        .HasDatabaseName("ix_access_token_records_jti");

                    b.HasIndex("RefreshSessionId")
                        .HasDatabaseName("ix_access_token_records_refresh_session_id");

                    b.HasIndex("AccountId", "ExpiresAtUtc", "RevokedAtUtc")
                        .HasDatabaseName("ix_access_token_records_account_id_expires_at_utc_revoked_at_utc");

                    b.ToTable("access_token_records", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("normalized_email")
                        .UseCollation("ascii_bin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PasswordHashVersion")
                        .HasColumnType("int")
                        .HasColumnName("password_hash_version");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("role_id");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("int")
                        .HasColumnName("security_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_normalized_email");

                    b.HasIndex("RoleId", "IsActive")
                        .HasDatabaseName("ix_accounts_role_id_is_active");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("account_id");

                    b.Property<int>("AccountSecurityVersion")
                        .HasColumnType("int")
                        .HasColumnName("account_security_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_used_at_utc");

                    b.Property<string>("ParentSessionId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("parent_session_id");

                    b.Property<string>("ReplacedBySessionId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTime?>("ReuseDetectedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reuse_detected_at_utc");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenFamilyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("token_family_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserAgentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("user_agent_hash");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_refresh_sessions");

                    b.HasIndex("ParentSessionId")
                        .HasDatabaseName("ix_refresh_sessions_parent_session_id");

                    b.HasIndex("TokenFamilyId")
                        .HasDatabaseName("ix_refresh_sessions_token_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_sessions_token_hash");

                    b.HasIndex("AccountId", "ExpiresAtUtc", "RevokedAtUtc")
                        .HasDatabaseName("ix_refresh_sessions_account_id_expires_at_utc_revoked_at_utc");

                    b.ToTable("refresh_sessions", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_system_role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Media.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at_utc");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<bool>("IsLinked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_linked");

                    b.Property<DateTime?>("LinkedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("linked_at_utc");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OwnerAccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("owner_account_id");

                    b.Property<int>("Purpose")
                        .HasColumnType("int")
                        .HasColumnName("purpose");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256hash");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("storage_provider");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<int>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_photos_storage_key");

                    b.HasIndex("OwnerAccountId", "IsLinked", "CreatedAtUtc")
                        .HasDatabaseName("ix_photos_owner_account_id_is_linked_created_at_utc");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Operations.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("action");

                    b.Property<string>("ActorAccountId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("actor_account_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntityId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserAgentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("user_agent_hash");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorAccountId", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_logs_actor_account_id_created_at_utc");

                    b.HasIndex("EntityType", "EntityId", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id_created_at_utc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Operations.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("encrypted_payload");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("lock_id");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("message_type");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("LockedUntilUtc")
                        .HasDatabaseName("ix_outbox_messages_locked_until_utc");

                    b.HasIndex("Status", "NextAttemptAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_status_next_attempt_at_utc_created_at_utc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.CheckoutRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("customer_account_id");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("endpoint");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("failure_code");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("idempotency_key")
                        .UseCollation("ascii_bin");

                    b.Property<string>("OrderId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("order_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("json")
                        .HasColumnName("response_json");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("response_status_code");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_checkout_requests");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_checkout_requests_expires_at_utc");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_checkout_requests_order_id");

                    b.HasIndex("CustomerAccountId", "Endpoint", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_checkout_requests_customer_account_id_endpoint_idempotency_k");

                    b.ToTable("checkout_requests", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("customer_account_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("order_number")
                        .UseCollation("ascii_bin");

                    b.Property<string>("ShippingAddressJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("shipping_address_json");

                    b.Property<decimal>("ShippingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipping_amount");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StockReturnedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("stock_returned_at_utc");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_order_number");

                    b.HasIndex("CustomerAccountId", "CreatedAtUtc")
                        .HasDatabaseName("ix_orders_customer_account_id_created_at_utc");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_orders_status_created_at_utc");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderPackageId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("order_package_id");

                    b.Property<string>("PhotoIdSnapshot")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("photo_id_snapshot");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("product_title_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("SellerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("seller_name_snapshot");

                    b.Property<string>("SellerProfileId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("seller_profile_id");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("OrderPackageId")
                        .HasDatabaseName("ix_order_items_order_package_id");

                    b.HasIndex("PhotoIdSnapshot")
                        .HasDatabaseName("ix_order_items_photo_id_snapshot");

                    b.HasIndex("SellerProfileId")
                        .HasDatabaseName("ix_order_items_seller_profile_id");

                    b.HasIndex("ProductId", "OrderId")
                        .HasDatabaseName("ix_order_items_product_id_order_id");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.OrderPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("order_id");

                    b.Property<string>("SellerProfileId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("seller_profile_id");

                    b.Property<string>("SellerStoreNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("seller_store_name_snapshot");

                    b.Property<decimal?>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipping_fee");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_order_packages");

                    b.HasIndex("OrderId", "Status")
                        .HasDatabaseName("ix_order_packages_order_id_status");

                    b.HasIndex("SellerProfileId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_order_packages_seller_profile_id_status_created_at_utc");

                    b.ToTable("order_packages", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CardBrand")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("card_brand");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("card_last4");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("customer_account_id");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("failure_code");

                    b.Property<string>("OrderId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CustomerAccountId")
                        .HasDatabaseName("ix_payments_customer_account_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payments_order_id");

                    b.HasIndex("Provider", "ProviderTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_provider_provider_transaction_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Profiles.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("account_id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address_line");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("district");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("AccountId", "IsActive")
                        .HasDatabaseName("ix_addresses_account_id_is_active");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Profiles.SellerProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoPhotoId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("logo_photo_id");

                    b.Property<decimal>("RatingAverage")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int")
                        .HasColumnName("rating_count");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("store_name");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tax_number");

                    b.Property<string>("TaxOffice")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("tax_office");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_seller_profiles");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_seller_profiles_account_id");

                    b.HasIndex("LogoPhotoId")
                        .HasDatabaseName("ix_seller_profiles_logo_photo_id");

                    b.HasIndex("IsActive", "StoreName")
                        .HasDatabaseName("ix_seller_profiles_is_active_store_name");

                    b.ToTable("seller_profiles", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Shopping.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("customer_account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_carts");

                    b.HasIndex("CustomerAccountId", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_carts_customer_account_id_is_active");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Shopping.CartItem", b =>
                {
                    b.Property<string>("CartId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("cart_id");

                    b.Property<string>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("added_at_utc");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("CartId", "ProductId")
                        .HasName("pk_cart_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_cart_items_product_id");

                    b.ToTable("cart_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_cart_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Shopping.Favorite", b =>
                {
                    b.Property<string>("CustomerAccountId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("customer_account_id");

                    b.Property<string>("ProductId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("added_at_utc");

                    b.HasKey("CustomerAccountId", "ProductId")
                        .HasName("pk_favorites");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_favorites_product_id");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.Category", b =>
                {
                    b.HasOne("ECommerce.Domain.Media.Photo", "IconPhoto")
                        .WithMany()
                        .HasForeignKey("IconPhotoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_categories_photos_icon_photo_id");

                    b.HasOne("ECommerce.Domain.Catalog.Category", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");

                    b.Navigation("IconPhoto");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.Product", b =>
                {
                    b.HasOne("ECommerce.Domain.Catalog.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("ECommerce.Domain.Profiles.SellerProfile", "SellerProfile")
                        .WithMany("Products")
                        .HasForeignKey("SellerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_seller_profiles_seller_profile_id");

                    b.Navigation("Category");

                    b.Navigation("SellerProfile");
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.ProductPhoto", b =>
                {
                    b.HasOne("ECommerce.Domain.Media.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_photos_photos_photo_id");

                    b.HasOne("ECommerce.Domain.Catalog.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_photos_products_product_id");

                    b.Navigation("Photo");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.Review", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "CustomerAccount")
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_accounts_customer_account_id");

                    b.HasOne("ECommerce.Domain.Catalog.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_products_product_id");

                    b.Navigation("CustomerAccount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.ReviewPhoto", b =>
                {
                    b.HasOne("ECommerce.Domain.Media.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_photos_photos_photo_id");

                    b.HasOne("ECommerce.Domain.Catalog.Review", "Review")
                        .WithMany("Photos")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_photos_reviews_review_id");

                    b.Navigation("Photo");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ECommerce.Domain.Fulfillment.Shipment", b =>
                {
                    b.HasOne("ECommerce.Domain.Orders.OrderPackage", "OrderPackage")
                        .WithOne("Shipment")
                        .HasForeignKey("ECommerce.Domain.Fulfillment.Shipment", "OrderPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_order_packages_order_package_id");

                    b.HasOne("ECommerce.Domain.Fulfillment.ShippingCarrier", "ShippingCarrier")
                        .WithMany("Shipments")
                        .HasForeignKey("ShippingCarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_shipping_carriers_shipping_carrier_id");

                    b.Navigation("OrderPackage");

                    b.Navigation("ShippingCarrier");
                });

            modelBuilder.Entity("ECommerce.Domain.Fulfillment.ShippingCarrier", b =>
                {
                    b.HasOne("ECommerce.Domain.Media.Photo", "LogoPhoto")
                        .WithMany()
                        .HasForeignKey("LogoPhotoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shipping_carriers_photos_logo_photo_id");

                    b.Navigation("LogoPhoto");
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.AccessTokenRecord", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "Account")
                        .WithMany("AccessTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_token_records_accounts_account_id");

                    b.HasOne("ECommerce.Domain.Identity.RefreshSession", "RefreshSession")
                        .WithMany("AccessTokens")
                        .HasForeignKey("RefreshSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_token_records_refresh_sessions_refresh_session_id");

                    b.Navigation("Account");

                    b.Navigation("RefreshSession");
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.Account", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "Account")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_sessions_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ECommerce.Domain.Media.Photo", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "OwnerAccount")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_photos_accounts_owner_account_id");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.CheckoutRequest", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "CustomerAccount")
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checkout_requests_accounts_customer_account_id");

                    b.HasOne("ECommerce.Domain.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_checkout_requests_orders_order_id");

                    b.Navigation("CustomerAccount");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.Order", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "CustomerAccount")
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_accounts_customer_account_id");

                    b.Navigation("CustomerAccount");
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Orders.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("ECommerce.Domain.Orders.OrderPackage", "OrderPackage")
                        .WithMany("Items")
                        .HasForeignKey("OrderPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_order_packages_order_package_id");

                    b.HasOne("ECommerce.Domain.Media.Photo", "PhotoSnapshot")
                        .WithMany()
                        .HasForeignKey("PhotoIdSnapshot")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_order_items_photos_photo_id_snapshot");

                    b.HasOne("ECommerce.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_products_product_id");

                    b.HasOne("ECommerce.Domain.Profiles.SellerProfile", "SellerProfile")
                        .WithMany()
                        .HasForeignKey("SellerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_seller_profiles_seller_profile_id");

                    b.Navigation("Order");

                    b.Navigation("OrderPackage");

                    b.Navigation("PhotoSnapshot");

                    b.Navigation("Product");

                    b.Navigation("SellerProfile");
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.OrderPackage", b =>
                {
                    b.HasOne("ECommerce.Domain.Orders.Order", "Order")
                        .WithMany("Packages")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_packages_orders_order_id");

                    b.HasOne("ECommerce.Domain.Profiles.SellerProfile", "SellerProfile")
                        .WithMany()
                        .HasForeignKey("SellerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_packages_seller_profiles_seller_profile_id");

                    b.Navigation("Order");

                    b.Navigation("SellerProfile");
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.Payment", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "CustomerAccount")
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_accounts_customer_account_id");

                    b.HasOne("ECommerce.Domain.Orders.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_orders_order_id");

                    b.Navigation("CustomerAccount");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerce.Domain.Profiles.Address", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "Account")
                        .WithMany("Addresses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ECommerce.Domain.Profiles.SellerProfile", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "Account")
                        .WithOne("SellerProfile")
                        .HasForeignKey("ECommerce.Domain.Profiles.SellerProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seller_profiles_accounts_account_id");

                    b.HasOne("ECommerce.Domain.Media.Photo", "LogoPhoto")
                        .WithMany()
                        .HasForeignKey("LogoPhotoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_seller_profiles_photos_logo_photo_id");

                    b.Navigation("Account");

                    b.Navigation("LogoPhoto");
                });

            modelBuilder.Entity("ECommerce.Domain.Shopping.Cart", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "CustomerAccount")
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_carts_accounts_customer_account_id");

                    b.Navigation("CustomerAccount");
                });

            modelBuilder.Entity("ECommerce.Domain.Shopping.CartItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Shopping.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_items_carts_cart_id");

                    b.HasOne("ECommerce.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cart_items_products_product_id");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Shopping.Favorite", b =>
                {
                    b.HasOne("ECommerce.Domain.Identity.Account", "CustomerAccount")
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_accounts_customer_account_id");

                    b.HasOne("ECommerce.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_products_product_id");

                    b.Navigation("CustomerAccount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ECommerce.Domain.Catalog.Review", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("ECommerce.Domain.Fulfillment.ShippingCarrier", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.Account", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("Addresses");

                    b.Navigation("RefreshSessions");

                    b.Navigation("SellerProfile");
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.RefreshSession", b =>
                {
                    b.Navigation("AccessTokens");
                });

            modelBuilder.Entity("ECommerce.Domain.Identity.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Packages");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ECommerce.Domain.Orders.OrderPackage", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ECommerce.Domain.Profiles.SellerProfile", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Shopping.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
