<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ECommerce.Infrastructure</RootNamespace>
    <AssemblyName>ECommerce.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Application\ECommerce.Application.csproj" />
    <ProjectReference Include="..\ECommerce.Domain\ECommerce.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Redis\Scripts\*.lua" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
